[package]
name = "third-wheel"
version = "0.1.0"
authors = ["Chris Campbell <campbellC@user.noreply.github.com>"]
edition = "2018"

[dependencies]
tokio = "=0.2.0-alpha.6"
openssl = "0.10.25"
httparse = "1.3.4"
clap = "2.33.0"
bytes = "0.4.12"
http = "0.1.19"
futures-util-preview = "0.3.0-alpha.19"
time = "0.1.42"
