[package]
name = "third-wheel"
version = "0.1.0"
authors = ["Chris Campbell <campbellC@user.noreply.github.com>"]
edition = "2018"

[dependencies]
tokio = "=0.2.0-alpha.6"
openssl = "0.10.25"
httparse = "1.3.4"