[package]
name = "third-wheel"
version = "0.2.0"
authors = ["Chris Campbell <campbellC@user.noreply.github.com>"]
edition = "2018"

[dependencies]
openssl = "0.10.30"
httparse = "1.3.4"
clap = "2.33.0"
bytes = "0.5.4"
http = "0.2.1"
futures-util-preview = "0.3.0-alpha.19"
futures = "0.3.5"
time = "0.1.42"
native-tls = "0.2.3"
# currently tokio-tls doesn't expose the native_tls TlsStream. To get access to certificates we need that so we use a fork
# https://github.com/tokio-rs/tokio/issues/1383
tokio-native-tls = "0.1.0"
#tokio-tls = { git = "https://github.com/campbellC/tokio", rev = "9f1158280a26f3682dc877720e0eea8e0da9663f"}
lazy_static = "1.4.0"

[dependencies.tokio]
version = "0.2.21"
features = ["macros", "rt-threaded", "tcp", "io-util", "tcp", "dns"]

[dependencies.tokio-util]
version = "0.3.1"
features = ["codec"]
