[package]
name = "third-wheel"
version = "0.1.0"
authors = ["Chris Campbell <campbellC@user.noreply.github.com>"]
edition = "2018"

[dependencies]
tokio = "=0.2.0-alpha.6"
openssl = "0.10.25"
httparse = "1.3.4"
clap = "2.33.0"
bytes = "0.4.12"
http = "0.1.19"
futures-util-preview = "0.3.0-alpha.19"
time = "0.1.42"
native-tls = "0.2.3"
# currently tokio-tls doesn't expose the native_tls TlsStream. To get access to certificates we need that so we use a fork
# https://github.com/tokio-rs/tokio/issues/1383
#tokio-tls = "0.3.0-alpha.6"
tokio-tls = { git = "https://github.com/campbellC/tokio", rev = "9f1158280a26f3682dc877720e0eea8e0da9663f", path="tokio-tls"}
lazy_static = "1.4.0"
